version: '3'
services: 
    web:
        build: .
        ports:
            - 3000:3000
        volumes: 
            - ./:/app
            - /app/node_modules
        tty: true
        working_dir: /app
        command: sh -c "yarn && yarn dev"